/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualInventoryRouteImport } from './routes/visual-inventory'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContainersIdRouteImport } from './routes/containers.$id'

const VisualInventoryRoute = VisualInventoryRouteImport.update({
  id: '/visual-inventory',
  path: '/visual-inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersIdRoute = ContainersIdRouteImport.update({
  id: '/containers/$id',
  path: '/containers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/visual-inventory': typeof VisualInventoryRoute
  '/containers/$id': typeof ContainersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/visual-inventory': typeof VisualInventoryRoute
  '/containers/$id': typeof ContainersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/visual-inventory': typeof VisualInventoryRoute
  '/containers/$id': typeof ContainersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/landing' | '/visual-inventory' | '/containers/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/landing' | '/visual-inventory' | '/containers/$id'
  id: '__root__' | '/' | '/landing' | '/visual-inventory' | '/containers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LandingRoute: typeof LandingRoute
  VisualInventoryRoute: typeof VisualInventoryRoute
  ContainersIdRoute: typeof ContainersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visual-inventory': {
      id: '/visual-inventory'
      path: '/visual-inventory'
      fullPath: '/visual-inventory'
      preLoaderRoute: typeof VisualInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers/$id': {
      id: '/containers/$id'
      path: '/containers/$id'
      fullPath: '/containers/$id'
      preLoaderRoute: typeof ContainersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LandingRoute: LandingRoute,
  VisualInventoryRoute: VisualInventoryRoute,
  ContainersIdRoute: ContainersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
